version: '3.9'

services:
  nestapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: directory-nest
    container_name: nest-app-db
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_CNN: ${MONGO_CNN}

  db:
    container_name: directory-app-db
    image: mongo:8.0.1
    ports:
      - '27018:27017'
    volumes:
      - nube-vol:/data/db
    restart: always
volumes:
  nube-vol:
    external: false