version: '3.9'

services:
  mongo:
    image: mongo:4.4-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: strider
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    restart: always
    volumes:
      - nube-data:/data/db
    networks:
      - nube-net
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    
  nestapp:
    image: sspa2/directory-nest
    container_name: nest-app-db
    restart: always
    networks:
      - nube-net
    env_file:
      - .env
    ports:
      - "9014:9014"
    environment:
      PORT: 9014
      MONGO_CNN: mongodb://strider:123456789@mongo:27017/
      APP_HOST: grupo5.lab

volumes:
  nube-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfs01,rw"
      device: ":/data/docker-vols/grupo5/nube-data"

networks:
  nube-net:
    driver: overlay
