version: '3.9'

services:
  mongo:
    image: mongo:8.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: always
    volumes:
      - nube-vol:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_CNN}
      ME_CONFIG_BASICAUTH: false
    restart: always
    
  nestapp:
    depends_on:
      - mongo
    build:
      context: .
    image: directory-nest
    container_name: nest-app-db
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_CNN: ${MONGO_CNN}

volumes:
  nube-vol:
    external: false