version: '3.9'

services:
  db:
    container_name: directory-app-DB
    image: mongo:8.0.1
    ports:
      - '27018:27017'
    volumes:
      - nube-vol:/data/db
    restart: always
volumes:
  nube-vol:
    external: false