version: '3.9'

services:
  db:
    restart: always
    container_name: directory-app-DB
    image: 95b
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27018:27017'