version: '3.9'

services:
  mongo:
    image: mongo:4.4-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: always
    volumes:
      - nube-vol:/data/db
    networks:
      - nube-net
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_CNN}
      ME_CONFIG_BASICAUTH: false
    restart: always
    networks:
      - nube-net
    
  nestapp:
    image: sspa2/directory-nest:1.0.0
    container_name: nest-app-db
    restart: always
    networks:
      - nube-net
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_CNN: ${MONGO_CNN}
      APP_HOST: ${APP_HOST}

volumes:
  nube-vol:
    # drive: local
    # driver-opts: 
    #   type: "nfs"
    #   o: "addr=nfs01.rw"
    #   device: ":/data/docker-vols/grupo9/nube-vol"
    external: false

networks:
  nube-net:
    driver: overlay
