version: '3.9'

services:
  mongo:
    image: mongo:8.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: always
    volumes:
      - nube-vol:/data/db
    networks:
      - nube-net
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_CNN}
      ME_CONFIG_BASICAUTH: false
    restart: always
    networks:
      - nube-net
    
  nestapp:
    build:
      context: .
    image: directory-nest
    container_name: nest-app-db
    restart: always
    networks:
      - nube-net
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_CNN: ${MONGO_CNN}
    depends_on:
        mongo:
          condition: service_healthy
          restart: true

volumes:
  nube-vol:
    external: false

networks:
  nube-net:

